name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Boost
      run: sudo apt-get install libboost-all-dev

    - name: Build and Run
      run: |
        g++ -o name_of_your_executable main.cpp -lboost_system
        ./name_of_your_executable
